export const ChampionsLeagueTeams = {
  FinalStage: {
    EuropaLeague: 1,
    England: 5,
    Spain: 5,
    Germany: 4,
    Italy: 4,
    France: 3,
    Netherlands: 2,
    Portugal: 1,
    Belgium: 1,
    Turkey: 1,
    Czech_Republic: 1,
    Greece: 1,
  },
  Playoff: {
    Scotland: 1,
    Switzerland: 1,
    Austria: 1,
    Norway: 1,
  },
  Q3: {
    France: 1,
    Netherlands: 1,
    Portugal: 1,
    Belgium: 1,
    Turkey: 1,
  },
  Q2: {
    Denmark: 1,
    Israel: 1,
    Ukraine: 1,
    Serbia: 1,
    Croatia: 1,
    Poland: 1,
    Cyprus: 1,
    Hungary: 1,
    Azerbaijan: 1,
    Slovakia: 1,
    Czech_Republic: 1,
    Greece: 1,
    Norway: 1,
    Austria: 1,
    Switzerland: 1,
    Scotland: 1,
  },
  Q1: {
    Sweden: 1,
    Romania: 1,
    Bulgaria: 1,
    Slovenia: 1,
    Moldova: 1,
    Kosovo: 1,
    Kazakhstan: 1,
    Finland: 1,
    Ireland: 1,
    Armenia: 1,
    Latvia: 1,
    Faroe_Islands: 1,
    Bosnia_and_Herzegovina: 1,
    Iceland: 1,
    Northern_Ireland: 1,
    Luxembourg: 1,
    Lithuania: 1,
    Malta: 1,
    Georgia: 1,
    Albania: 1,
    Estonia: 1,
    Belarus: 1,
    North_Macedonia: 1,
    Andorra: 1,
    Wales: 1,
    Montenegro: 1,
    Gibraltar: 1,
    San_Marino: 1,
  },
};

export const LibertadoresTeams = {
  FinalStage: {
    Libertadores: 1,
    Sudamericana: 1,
    Argentina: 5,
    Bolivia: 2,
    Brazil: 5,
    Chile: 2,
    Colombia: 2,
    Ecuador: 2,
    Paraguay: 2,
    Peru: 2,
    Uruguay: 2,
    Venezuela: 2,
  },
  Q2: {
    Argentina: 1,
    Bolivia: 1,
    Brazil: 2,
    Chile: 2,
    Colombia: 2,
    Ecuador: 1,
    Paraguay: 1,
    Peru: 1,
    Uruguay: 1,
    Venezuela: 1,
  },
  Q1: {
    Bolivia: 1,
    Ecuador: 1,
    Paraguay: 1,
    Peru: 1,
    Uruguay: 1,
    Venezuela: 1,
  },
};
