import type { Tournament } from "../types";

import PremierLeague_logo from "../../assets/icons/league logos/Premier_League_logo.png";
import LaLiga_logo from "../../assets/icons/league logos/LaLiga_logo.png";
import SerieA_logo from "../../assets/icons/league logos/SerieA_logo.png";
import Bundesliga_logo from "../../assets/icons/league logos/Bundesliga_logo.png";
import Ligue1_logo from "../../assets/icons/league logos/Ligue1_logo.png";
import Brasileirão_logo from "../../assets/icons/league logos/Brasileirão_logo.png";
import Eredivisie_logo from "../../assets/icons/league logos/Eredivisie_logo.png";

export const TournamentsList: Tournament[] = [
  {
    id: "premier_league",
    name: "Premier League",
    logo: PremierLeague_logo,
    primaryColor: "#37003C",
    secondaryColor: "#8252FF",
    tertiaryColor: "#48034f",
    backgroundColor: "#37003C",
    textColor: "#FFFFFF",
    teams: 20,
    relegated: 3,
    qualified: [5, 2], // Champions League / Europa League
    defaultTeams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Burnley",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Sunderland",
      "Tottenham",
      "West Ham United",
      "Wolves",
    ],
  },
  {
    id: "la_liga",
    name: "La Liga",
    logo: LaLiga_logo,
    primaryColor: "#ff6560",
    secondaryColor: "#ff6560",
    tertiaryColor: "#e9e5e5",
    backgroundColor: "#FFFFFF",
    textColor: "#08237F",
    teams: 20,
    relegated: 3,
    qualified: [5, 2], // Champions League / Europa League
    defaultTeams: [
      "Athletic Club",
      "Atlético Madrid",
      "Barcelona",
      "Celta",
      "Deportivo Alavés",
      "Elche",
      "Espanyol",
      "Getafe",
      "Girona",
      "Levante",
      "Mallorca",
      "Osasuna",
      "Rayo Vallecano",
      "Real Betis",
      "Real Madrid",
      "Real Oviedo",
      "Real Sociedad",
      "Sevilla",
      "Valencia",
      "Villarreal",
    ],
  },
  {
    id: "serie_a",
    name: "Serie A",
    logo: SerieA_logo,
    primaryColor: "#0C8CFF",
    secondaryColor: "#00F4E6",
    tertiaryColor: "#93fffa",
    backgroundColor: "#FFFFFF",
    textColor: "#024c8c",
    teams: 20,
    relegated: 3,
    qualified: [4, 2], // Champions League / Europa League
    defaultTeams: [
      "Atalanta",
      "Bologna",
      "Cagliari",
      "Como",
      "Cremonese",
      "Fiorentina",
      "Genoa",
      "Hellas Verona",
      "Internazionale",
      "Juventus",
      "Lazio",
      "Lecce",
      "Milan",
      "Napoli",
      "Parma",
      "Pisa",
      "Roma",
      "Sassuolo",
      "Torino",
      "Udinese",
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    logo: Bundesliga_logo,
    primaryColor: "#D10214",
    secondaryColor: "#D10214",
    tertiaryColor: "#1c2429",
    backgroundColor: "#0A141A",
    textColor: "#FFFFFF",
    teams: 18,
    relegated: 3,
    qualified: [4, 2], // Champions League / Europa League
    defaultTeams: [
      "Augsburg",
      "Bayer Leverkusen",
      "Bayern München",
      "Borussia Dortmund",
      "Borussia M'Gladbach",
      "Eintracht Frankfurt",
      "Freiburg",
      "Hamburger SV",
      "Heidenheim",
      "Hoffenheim",
      "Köln",
      "Mainz 05",
      "RB Leipzig",
      "St. Pauli",
      "Stuttgart",
      "Union Berlin",
      "Werder Bremen",
      "Wolfsburg",
    ],
  },
  {
    id: "ligue_1",
    name: "Ligue 1",
    logo: Ligue1_logo,
    primaryColor: "#0061FE",
    secondaryColor: "#0061FE",
    tertiaryColor: "#213744",
    backgroundColor: "#0d2534",
    textColor: "#FFFFFF",
    teams: 18,
    relegated: 3,
    qualified: [3, 3], // Champions League / Europa League
    defaultTeams: [
      "Angers",
      "AS Monaco",
      "Auxerre",
      "Brest",
      "Le Havre",
      "Lens",
      "Lille",
      "Lorient",
      "Lyon",
      "Marseille",
      "Metz",
      "Nantes",
      "Nice",
      "Paris FC",
      "Paris Saint-Germain",
      "Stade Rennais",
      "Strasbourg",
      "Toulouse",
    ],
  },
  {
    id: "eredivisie",
    name: "Eredivisie",
    logo: Eredivisie_logo,
    primaryColor: "#14094a",
    secondaryColor: "#14094a",
    tertiaryColor: "#3e368c",
    backgroundColor: "#39365b",
    textColor: "#FFFFFF",
    teams: 18,
    relegated: 3,
    qualified: [3, 3], // Champions League / Europa League
    defaultTeams: [
      "Ajax",
      "AZ Alkmaar",
      "Excelsior",
      "Feyenoord",
      "Fortuna Sittard",
      "Go Ahead Eagles",
      "Groningen",
      "Heerenveen",
      "Heracles Almelo",
      "NAC Breda",
      "Nijmegen",
      "PEC Zwolle",
      "PSV",
      "Sparta Rotterdam",
      "Telstar",
      "Twente",
      "Utrecht",
      "Volendam",
    ],
  },
  {
    id: "brasileirao",
    name: "Brasileirão",
    logo: Brasileirão_logo,
    primaryColor: "#C7FF00",
    secondaryColor: "#2b16c7",
    tertiaryColor: "#7967ff",
    backgroundColor: "#150942",
    textColor: "#FFFFFF",
    teams: 20,
    relegated: 4,
    qualified: [6, 6], // Libertadores / Sudamericana
    defaultTeams: [
      "Atlético-MG",
      "Bahia",
      "Botafogo",
      "Ceará",
      "Corinthians",
      "Cruzeiro",
      "Flamengo",
      "Fluminense",
      "Fortaleza",
      "Grêmio",
      "Internacional",
      "Juventude",
      "Mirassol",
      "Palmeiras",
      "RB Bragantino",
      "Santos",
      "São Paulo",
      "Sport",
      "Vasco",
      "Vitória",
    ],
  },
];
