import type { Tournament } from "../types";

import PremierLeague_logo from "../../assets/icons/league logos/Premier_League_logo.png";
import LaLiga_logo from "../../assets/icons/league logos/LaLiga_logo.png";
import SerieA_logo from "../../assets/icons/league logos/SerieA_logo.png";
import Bundesliga_logo from "../../assets/icons/league logos/Bundesliga_logo.png";
import Ligue1_logo from "../../assets/icons/league logos/Ligue1_logo.png";
import Brasileirão_logo from "../../assets/icons/league logos/Brasileirão_logo.png";
import Eredivisie_logo from "../../assets/icons/league logos/Eredivisie_logo.png";
import LigaPortugal_logo from "../../assets/icons/league logos/LigaPortugal_logo.png";
import SaudiProLeague_logo from "../../assets/icons/league logos/SaudiProLeague_logo.png";

import UefaChampionsLeague_logo from "../../assets/icons/league logos/UefaChampionsLeague_logo.png";
import Libertadores_logo from "../../assets/icons/league logos/Libertadores_logo.png";

export const TournamentsList: Tournament[] = [
  {
    id: "premier_league",
    name: "Premier League",
    logo: PremierLeague_logo,
    type: "National League",
    primaryColor: "#37003C",
    secondaryColor: "#8252FF",
    tertiaryColor: "#48034f",
    backgroundColor: "#37003C",
    textColor: "#FFFFFF",
    teams: 20,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [5, 2], // Champions League / Europa League
    defaultTeams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Burnley",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Sunderland",
      "Tottenham",
      "West Ham United",
      "Wolves",
    ],
  },
  {
    id: "la_liga",
    name: "La Liga",
    logo: LaLiga_logo,
    type: "National League",
    primaryColor: "#ff6560",
    secondaryColor: "#ff6560",
    tertiaryColor: "#e9e5e5",
    backgroundColor: "#FFFFFF",
    textColor: "#08237F",
    teams: 20,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [5, 2], // Champions League / Europa League
    defaultTeams: [
      "Athletic Club",
      "Atlético Madrid",
      "Barcelona",
      "Celta",
      "Deportivo Alavés",
      "Elche",
      "Espanyol",
      "Getafe",
      "Girona",
      "Levante",
      "Mallorca",
      "Osasuna",
      "Rayo Vallecano",
      "Real Betis",
      "Real Madrid",
      "Real Oviedo",
      "Real Sociedad",
      "Sevilla",
      "Valencia",
      "Villarreal",
    ],
  },
  {
    id: "serie_a",
    name: "Serie A",
    logo: SerieA_logo,
    type: "National League",
    primaryColor: "#0C8CFF",
    secondaryColor: "#00F4E6",
    tertiaryColor: "#93fffa",
    backgroundColor: "#FFFFFF",
    textColor: "#024c8c",
    teams: 20,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [4, 2], // Champions League / Europa League
    defaultTeams: [
      "Atalanta",
      "Bologna",
      "Cagliari",
      "Como",
      "Cremonese",
      "Fiorentina",
      "Genoa",
      "Hellas Verona",
      "Internazionale",
      "Juventus",
      "Lazio",
      "Lecce",
      "Milan",
      "Napoli",
      "Parma",
      "Pisa",
      "Roma",
      "Sassuolo",
      "Torino",
      "Udinese",
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    logo: Bundesliga_logo,
    type: "National League",
    primaryColor: "#D10214",
    secondaryColor: "#D10214",
    tertiaryColor: "#1c2429",
    backgroundColor: "#0A141A",
    textColor: "#FFFFFF",
    teams: 18,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [4, 2], // Champions League / Europa League
    defaultTeams: [
      "Augsburg",
      "Bayer Leverkusen",
      "Bayern München",
      "Borussia Dortmund",
      "Borussia M'Gladbach",
      "Eintracht Frankfurt",
      "Freiburg",
      "Hamburger SV",
      "Heidenheim",
      "Hoffenheim",
      "Köln",
      "Mainz 05",
      "RB Leipzig",
      "St. Pauli",
      "Stuttgart",
      "Union Berlin",
      "Werder Bremen",
      "Wolfsburg",
    ],
  },
  {
    id: "ligue_1",
    name: "Ligue 1",
    logo: Ligue1_logo,
    type: "National League",
    primaryColor: "#0061FE",
    secondaryColor: "#0061FE",
    tertiaryColor: "#213744",
    backgroundColor: "#0d2534",
    textColor: "#FFFFFF",
    teams: 18,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [3, 3], // Champions League / Europa League
    defaultTeams: [
      "Angers",
      "AS Monaco",
      "Auxerre",
      "Brest",
      "Le Havre",
      "Lens",
      "Lille",
      "Lorient",
      "Lyon",
      "Marseille",
      "Metz",
      "Nantes",
      "Nice",
      "Paris FC",
      "Paris Saint-Germain",
      "Stade Rennais",
      "Strasbourg",
      "Toulouse",
    ],
  },
  {
    id: "eredivisie",
    name: "Eredivisie",
    logo: Eredivisie_logo,
    type: "National League",
    primaryColor: "#14094a",
    secondaryColor: "#14094a",
    tertiaryColor: "#3e368c",
    backgroundColor: "#39365b",
    textColor: "#FFFFFF",
    teams: 18,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [3, 3], // Champions League / Europa League
    defaultTeams: [
      "Ajax",
      "AZ Alkmaar",
      "Excelsior",
      "Feyenoord",
      "Fortuna Sittard",
      "Go Ahead Eagles",
      "Groningen",
      "Heerenveen",
      "Heracles Almelo",
      "NAC Breda",
      "Nijmegen",
      "PEC Zwolle",
      "PSV",
      "Sparta Rotterdam",
      "Telstar",
      "Twente",
      "Utrecht",
      "Volendam",
    ],
  },
  {
    id: "liga_portugal",
    name: "Liga Portugal",
    logo: LigaPortugal_logo,
    type: "National League",
    primaryColor: "#257f09",
    secondaryColor: "#257f09",
    tertiaryColor: "#97cb8e",
    backgroundColor: "#420a0a",
    textColor: "#FFFFFF",
    teams: 18,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [2, 2], // Champions League / Europa League
    defaultTeams: [
      "Alverca",
      "Arouca",
      "AVS",
      "Benfica",
      "Braga",
      "Casa Pia",
      "Estoril",
      "Estrela Amadora",
      "Famalicão",
      "Gil Vicente",
      "Nacional",
      "Moreirense",
      "Porto",
      "Rio Ave",
      "Santa Clara",
      "Sporting",
      "Tondela",
      "Vitória de Guimarães",
    ],
  },
  {
    id: "brasileirao",
    name: "Brasileirão",
    logo: Brasileirão_logo,
    type: "National League",
    primaryColor: "#150942",
    secondaryColor: "#4337c8",
    tertiaryColor: "#096713",
    backgroundColor: "#150942",
    textColor: "#FFFFFF",
    teams: 20,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 4,
    qualified: [6, 6], // Libertadores / Sudamericana
    defaultTeams: [
      "Athletico-PR",
      "Atlético-MG",
      "Bahia",
      "Botafogo",
      "Chapecoense",
      "Coritiba",
      "Corinthians",
      "Cruzeiro",
      "Flamengo",
      "Fluminense",
      "Grêmio",
      "Internacional",
      "Mirassol",
      "Palmeiras",
      "RB Bragantino",
      "Remo",
      "Santos",
      "São Paulo",
      "Vasco",
      "Vitória",
    ],
  },
  {
    id: "saudi_league",
    name: "Saudi Pro League",
    logo: SaudiProLeague_logo,
    type: "National League",
    primaryColor: "#154f36",
    secondaryColor: "#11077d",
    tertiaryColor: "#0f0623",
    backgroundColor: "#cbcbcb",
    textColor: "#0d9f60",
    teams: 18,
    navbarItems: ["Teams Selection", "Matches", "Standings", "Statistics"],
    relegated: 3,
    qualified: [3, 0], // AFC Champions League
    defaultTeams: [
      "Al-Ahli",
      "Al-Ettifaq",
      "Al-Fateh",
      "Al-Fayha",
      "Al-Hazem",
      "Al-Hilal",
      "Al-Ittihad",
      "Al-Khaleej",
      "Al-Kholood",
      "Al-Najma",
      "Al-Nassr",
      "Al-Okhdood",
      "Al-Qadsiah",
      "Al-Riyadh",
      "Al-Shabab",
      "Al-Taawoun",
      "Damac",
      "Neom SC",
    ],
  },
  {
    id: "uefa_champions_league",
    name: "Champions League",
    logo: UefaChampionsLeague_logo,
    type: "Continental",
    primaryColor: "#120d4b",
    secondaryColor: "#180c93",
    tertiaryColor: "#180c93",
    backgroundColor: "#120d4b",
    textColor: "#FFFFFF",
    teams: 82,
    navbarItems: [
      "Teams Selection",
      "Qualifying Rounds",
      "Standings",
      "Knockout Stage",
      "Statistics",
    ],
    relegated: 0,
    qualified: [8, 16], // Round of 16 / Round of 32
    qualifyingPhases: [
      "1st Qualifying",
      "2nd Qualifying",
      "3rd Qualifying",
      "Playoff",
    ],
    defaultTeams: [
      "Tottenham",
      "Arsenal",
      "Chelsea",
      "Liverpool",
      "Manchester City",
      "Newcastle United",
      "Atlético Madrid",
      "Athletic Club",
      "Barcelona",
      "Real Madrid",
      "Villarreal",
      "Bayern München",
      "Bayer Leverkusen",
      "Borussia Dortmund",
      "Eintracht Frankfurt",
      "Atalanta",
      "Juventus",
      "Internazionale",
      "Napoli",
      "Paris Saint-Germain",
      "AS Monaco",
      "Marseille",
      "PSV",
      "Ajax",
      "Sporting",
      "Union SG",
      "Galatasaray",
      "Slavia Praha",
      "Olympiacos",
      "Celtic",
      "Basel",
      "Sturm Graz",
      "Bodo/Glimt",
      "Nice",
      "Feyenoord",
      "Benfica",
      "Club Brugge",
      "Fenerbahçe",
      "FC Kobenhavn",
      "Maccabi Tel-Aviv",
      "Dynamo Kyiv",
      "Crvena Zvezda",
      "Rijeka",
      "Lech Poznan",
      "Pafos",
      "Ferencváros",
      "Qarabag FK",
      "Slovan Bratislava",
      "Viktoria Plzen",
      "Panathinaikos",
      "SK Brann",
      "RB Salzburg",
      "Servette FC",
      "Rangers",
      "Malmö",
      "FCSB",
      "Ludogorets",
      "Olimpija Ljubliana",
      "FC Milsami Orhei",
      "FC Drita",
      "Kairat Almaty",
      "KuPS",
      "Shelbourne",
      "FC Noah",
      "RFS",
      "Víkingur Gota",
      "Zrinjski Mostar",
      "Breidablik",
      "Linfield FC",
      "Differdange 03",
      "FK Zalgiris",
      "Hamrun Spartans FC",
      "FC Iberia 1999",
      "KF Egnatia",
      "FCI Levadia Tallin",
      "Dinamo Minsk",
      "KF Shkëndija",
      "Inter d'Escaldes",
      "The New Saints",
      "FK Buducnost",
      "Lincoln Red Imps",
      "SS Virtus",
    ],
  },
  {
    id: "libertadores",
    name: "Libertadores",
    logo: Libertadores_logo,
    type: "Continental",
    primaryColor: "#AA7125",
    secondaryColor: "#AA7125",
    tertiaryColor: "#AA7125",
    backgroundColor: "#373737",
    textColor: "#FFFFFF",
    teams: 47,
    navbarItems: [
      "Teams Selection",
      "Qualifying Rounds",
      "Groups",
      "Knockout Stage",
      "Statistics",
    ],
    relegated: 0,
    qualifyingPhases: ["1st Qualifying", "2nd Qualifying", "3rd Qualifying"],
    defaultTeams: [
      "Flamengo",
      "Lanús",
      "Boca Juniors",
      "Estudiantes LP",
      "Ind. Rivadavia",
      "Platense",
      "Rosario Central",
      "Always Ready",
      "Bolívar",
      "Corinthians",
      "Cruzeiro",
      "Fluminense",
      "Mirassol",
      "Palmeiras",
      "Coquimbo Unido",
      "Universidad Católica",
      "Ind. Santa Fé",
      "Junior Barranquilla",
      "Ind. del Valle",
      "LDU Quito",
      "Cerro Porteño",
      "Club Libertad",
      "Cusco",
      "Universitario",
      "Nacional",
      "Peñarol",
      "Deportivo La Guaira",
      "Universidad Central",
      "Argentinos Jrs",
      "Nacional Potosí",
      "Bahia",
      "Botafogo",
      "Huachipato",
      "O'Higgins",
      "Deportes Tolima",
      "Ind. Medellín",
      "Barcelona SC",
      "Club Guaraní",
      "Sporting Cristal",
      "Liverpool (URU)",
      "Carabobo",
      "The Strongest",
      "U. Católica (ECU)",
      "2 De Mayo",
      "Alianza Lima",
      "Juventud",
      "Deportivo Táchira",
    ],
  },
];
