import type { Tournament } from "../types";

import PremierLeague_logo from "../../assets/icons/league logos/Premier_League_logo.png";
import LaLiga_logo from "../../assets/icons/league logos/LaLiga_logo.png";
import SerieA_logo from "../../assets/icons/league logos/SerieA_logo.png";
import Bundesliga_logo from "../../assets/icons/league logos/Bundesliga_logo.png";
import Ligue1_logo from "../../assets/icons/league logos/Ligue1_logo.png";
import Brasileirão_logo from "../../assets/icons/league logos/Brasileirão_logo.png";

export const TournamentsList: Tournament[] = [
  {
    id: "premier_league",
    name: "Premier League",
    logo: PremierLeague_logo,
    primaryColor: "#37003C",
    secondaryColor: "#8252FF",
    backgroundColor: "#37003C",
    textColor: "#FFFFFF",
    teams: 20,
    defaultTeams: [
      "arsenal",
      "aston_villa",
      "bournemouth",
      "brentford",
      "brighton",
      "burnley",
      "chelsea",
      "crystal_palace",
      "everton",
      "fulham",
      "leeds_united",
      "liverpool",
      "manchester_city",
      "manchester_united",
      "newcastle",
      "nottingham_forest",
      "sunderland",
      "tottenham",
      "west_ham_united",
      "wolves",
    ],
  },
  {
    id: "la_liga",
    name: "La Liga",
    logo: LaLiga_logo,
    primaryColor: "#ff6560",
    secondaryColor: "#ff6560",
    backgroundColor: "#FFFFFF",
    textColor: "#08237F",
    teams: 20,
    defaultTeams: [
      "athletic_club",
      "atletico_madrid",
      "barcelona",
      "celta",
      "deportivo_alaves",
      "elche",
      "espanyol",
      "getafe",
      "girona",
      "levante",
      "mallorca",
      "osasuna",
      "rayo_vallecano",
      "real_betis",
      "real_madrid",
      "real_oviedo",
      "real_sociedad",
      "sevilla",
      "valencia",
      "villarreal",
    ],
  },
  {
    id: "serie_a",
    name: "Serie A",
    logo: SerieA_logo,
    primaryColor: "#0C8CFF",
    secondaryColor: "#00F4E6",
    backgroundColor: "#FFFFFF",
    textColor: "#0C8CFF",
    teams: 20,
    defaultTeams: [
      "atalanta",
      "bologna",
      "cagliari",
      "como",
      "cremonese",
      "fiorentina",
      "genoa",
      "hellas_verona",
      "internazionale",
      "juventus",
      "lazio",
      "lecce",
      "milan",
      "napoli",
      "parma",
      "pisa",
      "roma",
      "sassuolo",
      "torino",
      "udinese",
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    logo: Bundesliga_logo,
    primaryColor: "#D10214",
    secondaryColor: "#D10214",
    backgroundColor: "#0A141A",
    textColor: "#FFFFFF",
    teams: 18,
    defaultTeams: [
      "augsburg",
      "bayer_leverkusen",
      "bayern_münchen",
      "borussia_dortmund",
      "borussia_gladbach",
      "eintracht_frankfurt",
      "freiburg",
      "hamburger",
      "heidenheim",
      "hoffenheim",
      "köln",
      "mainz",
      "rb_leipzig",
      "st_pauli",
      "stuttgart",
      "union_berlin",
      "werder_bremen",
      "wolfsburg",
    ],
  },
  {
    id: "ligue_1",
    name: "Ligue 1",
    logo: Ligue1_logo,
    primaryColor: "#0061FE",
    secondaryColor: "#0061FE",
    backgroundColor: "#0d2534",
    textColor: "#FFFFFF",
    teams: 18,
    defaultTeams: [
      "angers",
      "monaco",
      "auxerre",
      "brest",
      "le_havre",
      "lens",
      "lille",
      "lorient",
      "lyon",
      "marseille",
      "metz",
      "nantes",
      "nice",
      "paris_fc",
      "psg",
      "stade_rennais",
      "strasbourg",
      "toulouse",
    ],
  },
  {
    id: "brasileirao",
    name: "Brasileirão",
    logo: Brasileirão_logo,
    primaryColor: "#C7FF00",
    secondaryColor: "#2b16c7",
    backgroundColor: "#150942",
    textColor: "#FFFFFF",
    teams: 20,
    defaultTeams: [
      "atlético_mg",
      "bahia",
      "botafogo",
      "ceara",
      "corinthians",
      "cruzeiro",
      "flamengo",
      "fluminense",
      "fortaleza",
      "grêmio",
      "internacional",
      "juventude",
      "mirassol",
      "palmeiras",
      "rb_bragantino",
      "santos",
      "são_paulo",
      "sport",
      "vasco",
      "vitória",
    ],
  },
];
