export const CONMEBOL_Ranking = [
  "Palmeiras",
  "Flamengo",
  "River Plate",
  "Boca Juniors",
  "Peñarol",
  "Atlético-MG",
  "São Paulo",
  "Nacional",
  "Racing Club",
  "LDU Quito",
  "Fluminense",
  "Athletico-PR",
  "Internacional",
  "Grêmio",
  "Olimpia",
  "Ind. del Valle",
  "Club Libertad",
  "Estudiantes LP",
  "Botafogo",
  "Cerro Porteño",
  "Lanús",
  "Corinthians",
  "Bolívar",
  "Independiente",
  "Colo Colo",
  "Vélez Sarsfield",
  "Santos",
  "Barcelona SC",
  "Cruzeiro",
  "Atlético Nacional",
  "Fortaleza",
  "Universitario",
  "Defensa Y Justicia",
  "Junior Barranquilla",
  "Universidad Católica",
  "América de Cali",
  "San Lorenzo",
  "Sporting Cristal",
  "Universidad de Chile",
  "Alianza Lima",
  "The Strongest",
  "Emelec",
  "RB Bragantino",
  "Club Guaraní",
  "Ind. Medellín",
  "Talleres",
  "Argentinos Jrs",
  "Rosario Central",
  "Melgar",
  "Deportivo Táchira",
  "Deportivo Cali",
  "Palestino",
  "Ind. Santa Fé",
  "Millonarios",
  "Jorge Wilstermann",
  "Caracas FC",
  "Deportes Tolima",
  "Once Caldas",
  "Newell's Old Boys",
  "U. Católica (ECU)",
  "Vasco",
  "Huracán",
  "Bahia",
  "Always Ready",
  "Atlético-GO",
  "Godoy Cruz",
  "Deportivo Pereira",
  "Unión Española",
  "Huachipato",
  "Ceará",
  "Central Córdoba",
  "Cienciano",
  "Danubio",
  "América-MG",
  "Delfín",
  "Defensor Sporting",
  "Unión La Calera",
  "Coquimbo Unido",
  "Mushuc Runa",
  "Liverpool (URU)",
  "Atlético Bucaramanga",
  "Oriente Petrolero",
  "Cuiabá",
  "Nacional Asunción",
  "Unión Santa Fé",
  "Nacional Potosí",
  "Metropolitanos",
  "Montevideo Wanderers",
  "Goiás",
  "Ñublense",
  "Audax Italiano",
  "Aucas",
  "Estudiantes de Mérida",
  "Monagas SC",
  "San Antonio",
  "Sportivo Luqueño",
  "Everton de Viña",
  "Deportivo La Guaira",
  "Puerto Cabello",
  "Boston River",
  "Carabobo",
  "Cobresal",
  "Vitória",
  "Atlético Grau",
  "Montevideo City",
  "Deportivo Garcilaso",
  "Zamora FC",
  "Gimnasia LP",
  "Cusco",
  "Ind. Petrolero",
  "Sport",
  "Sportivo Trinidense",
  "O'Higgins",
  "Real Tomayapo",
  "Club Aurora",
  "Platense",
  "2 De Mayo",
  "Juventud",
  "Ind. Rivadavia",
  "Mirassol",
];
