export const UEFA_Ranking = [
  "Real Madrid",
  "Bayern München",
  "Internazionale",
  "Manchester City",
  "Liverpool",
  "Paris Saint-Germain",
  "Borussia Dortmund",
  "Bayer Leverkusen",
  "Barcelona",
  "Arsenal",
  "Atlético Madrid",
  "Chelsea",
  "Roma",
  "Benfica",
  "Eintracht Frankfurt",
  "Atalanta",
  "Manchester United",
  "PSV",
  "Club Brugge",
  "Sporting",
  "Feyenoord",
  "West Ham United",
  "Tottenham",
  "Fiorentina",
  "Milan",
  "Juventus",
  "Lille",
  "Porto",
  "Napoli",
  "RB Leipzig",
  "Real Betis",
  "Villarreal",
  "Lazio",
  "Rangers",
  "Real Sociedad",
  "Aston Villa",
  "Bodo/Glimt",
  "Olympiacos",
  "Ajax",
  "Fenerbahçe",
  "AZ Alkmaar",
  "AS Monaco",
  "Marseille",
  "Lyon",
  "FC Kobenhavn",
  "Galatasaray",
  "Union SG",
  "Slavia Praha",
  "Braga",
  "Shakhtar Donetsk",
  "Dinamo Zagreb",
  "Viktoria Plzen",
  "PAOK",
  "RB Salzburg",
  "Ferencváros",
  "Qarabag FK",
  "Celtic",
  "Crvena Zvezda",
  "Gent",
  "Sevilla",
  "Freiburg",
  "Athletic Club",
  "Stade Rennais",
  "Midtjylland",
  "Basel",
  "Slovan Bratislava",
  "Djurgardens IF",
  "Anderlecht",
  "Sparta Praha",
  "Legia Warsaw",
  "Maccabi Tel-Aviv",
  "Young Boys",
  "Rapid Wien",
  "Sturm Graz",
  "Ludogorets",
  "Union Berlin",
  "FCSB",
  "Pafos",
  "Panathinaikos",
  "Partizan",
  "Molde",
  "LASK",
  "Newcastle United",
  "Nottingham Forest",
  "Crystal Palace",
  "Brighton",
  "Leicester City",
  "Jagiellonia",
  "Lech Poznan",
  "Sheriff Tiraspol",
  "Stuttgart",
  "Vitória de Guimarães",
  "Omonia",
  "Olimpija Ljubliana",
  "Bologna",
  "Genk",
  "Celje",
  "CFR Cluj",
  "Maccabi Haifa",
  "Shamrock Rovers",
  "Nice",
  "Celta",
  "Rayo Vallecano",
  "Girona",
  "Osasuna",
  "Brest",
  "Mainz 05",
  "Heidenheim",
  "Hoffenheim",
  "Köln",
  "Wolfsburg",
  "Besiktas",
  "Dynamo Kyiv",
  "Apoel",
  "Strasbourg",
  "Lens",
  "Toulouse",
  "Nantes",
  "Raków Czestochowa",
  "HJK Helsinki",
  "Hapoel Tel-Aviv",
  "Twente",
  "FC Drita",
  "Rijeka",
  "Malmö",
  "Go Ahead Eagles",
  "Utrecht",
  "RFS",
  "Servette FC",
  "Astana",
  "Royal Antwerp",
  "Santa Clara",
  "Arouca",
  "Gil Vicente",
  "Zrinjski Mostar",
  "FK Zalgiris",
  "Zorya Luhansk",
  "Vikingur Reykjavík",
  "AEK Athens",
  "KuPS",
  "Lincoln Red Imps",
  "Hearts",
  "Kairat Almaty",
  "SK Brann",
  "Trabzonspor",
  "Universitatea Craiova",
  "Riga FC",
  "KI Klaksvík",
  "Spartak Trnava",
  "KF Ballkani",
  "Hajduk Split",
  "Breidablik",
  "Pyunik Yerevan",
  "NK Maribor",
  "Flora Tallin",
  "Brondby",
  "Linfield FC",
  "Häcken",
  "Larne FC",
  "Petrocub",
  "The New Saints",
  "KF Shkëndija",
  "FC Noah",
  "Hamrun Spartans FC",
  "F91 Dudelange",
  "FC Tobol",
  "Rosenborg",
  "FC Milsami Orhei",
  "FCI Levadia Tallin",
  "Paide Linnameeskond",
  "Inter d'Escaldes",
  "FK Buducnost",
  "Partizani",
  "Levski Sofia",
  "HB Tórshavn",
  "Zürich",
  "Differdange 03",
  "Dinamo Minsk",
  "Neftçi",
  "CSKA Sofia",
  "Víkingur Gota",
  "Kauno Zalgiris",
  "FK Sutjeska",
  "La Fiorita",
  "Dinamo Batumi",
  "MSK Zilina",
  "Vojvodina",
  "BATE Borisov",
  "FC Iberia 1999",
  "FK Sarajevo",
  "Santa Coloma",
  "FC Struga",
  "Dinamo Tbilisi",
  "Alashkert",
  "Debreceni VSC",
  "KF Egnatia",
  "Valur Reykjavík",
  "SP Tre Penne",
  "SS Virtus",
  "Derry City",
  "KF Tirana",
  "Birkirkara FC",
  "Shelbourne",
  "Europa FC",
  "Penybont",
];
